name: deploy-prod
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        required: false
        default: 'PROD'
  push:
    branches:
      - master

jobs:
  build:
    environment: ${{ github.event.inputs.environment || 'PROD' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

#      - name: Test
#        run: yarn test

      - name: Production Dependencies
        run: yarn --production

      - name: Setup Package
        env:
          GCP_FUNCTION_VARIABLES: ${{ secrets.GCP_FUNCTION_VARIABLES }}
        run: |
          echo "GCP_FUNCTION_VARIABLES" >> .env.yml
          cp package.json dist/package.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: 'ecommerce'
          runtime: 'nodejs14'
          entry_point: 'api'
          region: 'southamerica-east1'
          source_dir: 'dist'
          env_vars_file: '.env.yml'
